apiVersion: batch/v1
kind: CronJob
metadata:
  name: automagic-server-monitor-cronjob
  namespace: automagic-developer
  labels:
    name: automagic-server-monitor-pod
    environment: production
    service-type: monitor
    app: automagic-developer
spec:
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          name: automagic-server-monitor-cronjob
          namespace: automagic-developer
          labels:
            name: automagic-server-monitor-cronjob
            environment: production
            service-type: monitor
            app: automagic-developer
          annotations:
            imageregistry: "https://hub.docker.com/"
        spec:
          securityContext:
              runAsUser: 99
          imagePullSecrets:
            - name: dockerhub-secret
          restartPolicy: OnFailure
          containers:
            - name: server-monitor
              image: mabdelgawad94/automagic_developer:server_monitor-f00335e
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "10M"
                  cpu: 0.01
                limits:
                  memory: "2G"
                  cpu: 2
              envFrom:
                - configMapRef:
                    name: automagic-cm
                - secretRef:
                    name: automagic-secrets
              securityContext:
                allowPrivilegeEscalation: true
