apiVersion: v1
kind: PersistentVolume
metadata:
  name: automagic-db-data-pv
  namespace: automagic-developer
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nfs/automagic_stack/db_data/
    server: 157.230.12.200
