apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automagic-db-data-pvc
  namespace: automagic-developer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
  storageClassName: nfs
