apiVersion: v1
kind: PersistentVolume
metadata:
  name: automagic-app-media-pv
  namespace: automagic-developer
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nfs/automagic_stack/app_media
    server: 157.230.12.200
