apiVersion: v1
kind: LimitRange
metadata:
  name: automagic-container-limit-ranges
  namespace: automagic-developer
spec:
  limits:
    - default: # this section defines default limits
        cpu: 1000m
        memory: 1G
      defaultRequest: # this section defines default requests
        cpu: 10m
        memory: 10M
      max: # max and min define the limit range
        cpu: 2000m
        memory: 2G
      min:
        cpu: 1m
        memory: 1M
      type: Container
